#!/bin/sh

# You need pandoc and sed to get the pdf of the guide. Then run this without
# arguments and a pdf file will be created in the current directory

echo Converting from Markdown to LaTeX
pandoc --no-wrap -f markdown -t latex ../using_git.md > pandoc_output.tex

sed -i 's/includegraphics/img/' pandoc_output.tex
sed -i '/This is the workflow we are going to use/i begin{quote}' pandoc_output.tex
sed -i '/This is the workflow we are going to use/a end{quote}' pandoc_output.tex
sed -r -i 's/^(begin|end)/\\&/' pandoc_output.tex
sed -i 's/{enumerate}\[1\.\]/{enumerate}/' pandoc_output.tex
sed -r -i 's/^(\\img.*$)/\n&\n/' pandoc_output.tex
sed -r -i 's/(\\begin\{verbatim\}*$)/\n\\begin{small}\n\\begin{shaded}\n&/' pandoc_output.tex
sed -r -i 's/(\\end\{verbatim\}*$)/&\n\\end{shaded}\n\\end{small}\n/' pandoc_output.tex
sed -r -i 's/verb!(\w+?)!/texttt{\1}/g' pandoc_output.tex
sed -r -i 's/Analysis_files/Analysis\\_files/g' pandoc_output.tex

echo Creating using_git.pdf
pdflatex using_git.tex
pdflatex using_git.tex
echo Done.
